// products.js
const products = [
  {
    id: 1,
    name: 'RGB Headphones',
    brand: 'BoAt',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'electronics',
    sold: 7489,
    image: 'images/products/headphones.jpeg',
    popular: true,
  },
  {
    id: 2,
    name: 'Mobile',
    brand: 'IQOO',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'electronics',
    sold: 7489,
    image: 'images/products/mobile.jpeg',
    popular: true,
  },
  {
    id: 3,
    name: 'Laptop',
    brand: 'Asus RoG',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'electronics',
    sold: 7489,
    image: 'images/products/laptop.jpeg',
    popular: true,
  },
  {
    id: 4,
    name: 'Gaming Mouse',
    brand: 'LogiTech',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'electronics',
    sold: 7489,
    image: 'images/products/mouse.jpeg',
    popular: true,
  },
  {
    id: 5,
    name: 'Designer Bed',
    brand: 'Ikea',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'furniture',
    sold: 7489,
    image: 'images/products/bed.jpeg',
    popular: false,
  },
  {
    id: 6,
    name: 'Dining Table',
    brand: 'Dining',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'furniture',
    sold: 7489,
    image: 'images/products/dining.jpeg',
    popular: true,
  },
  {
    id: 7,
    name: 'Designer Bed Sheet',
    brand: 'CarlOn',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'furniture',
    sold: 7489,
    image: 'images/products/bedsheet.jpeg',
    popular: false,
  },
  {
    id: 8,
    name: 'Comfy Chair',
    brand: 'LogiTech',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'furniture',
    sold: 7489,
    image: 'images/products/chair.jpeg',
    popular: false,
  },
  {
    id: 9,
    name: 'Wool Cushions',
    brand: 'Wooly',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'furniture',
    sold: 7489,
    image: 'images/products/pillow.jpeg',
    popular: false,
  },
  {
    id: 10,
    name: '3-in-1 Sofa',
    brand: 'Ikea',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'furniture',
    sold: 7489,
    image: 'images/products/sofa.jpeg',
    popular: true,
  },
  {
    id: 11,
    name: 'Centre Table',
    brand: 'Wood Works',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'furniture',
    sold: 7489,
    image: 'images/products/table.jpeg',
    popular: false,
  },
  {
    id: 12,
    name: 'Clothes Wardrobe',
    brand: 'Org-Drobe',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'furniture',
    sold: 7489,
    image: 'images/products/wardrobe.jpeg',
    popular: false,
  },
  {
    id: 13,
    name: 'Air Jordan Shoes',
    brand: 'Nike',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'shoes',
    sold: 7489,
    image: 'images/products/shoes1.jpeg',
    popular: true,
  },
  {
    id: 14,
    name: 'Nike Running Shoes',
    brand: 'Nike',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'shoes',
    sold: 7489,
    image: 'images/products/shoes2.jpeg',
    popular: false,
  },
  {
    id: 15,
    name: 'Puma Jogging Shoes',
    brand: 'Puma',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'shoes',
    sold: 7489,
    image: 'images/products/shoes3.jpeg',
    popular: false,
  },
  {
    id: 16,
    name: 'Campus Gym Shoes',
    brand: 'Campus',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'shoes',
    sold: 7489,
    image: 'images/products/shoes4.jpeg',
    popular: true,
  },
  {
    id: 17,
    name: 'Running Shoes',
    brand: 'Ajanta',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'shoes',
    sold: 7489,
    image: 'images/products/shoes5.jpeg',
    popular: false,
  },
  {
    id: 18,
    name: 'Bata Office Shoes',
    brand: 'Bata',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'shoes',
    sold: 7489,
    image: 'images/products/shoes6.jpeg',
    popular: true,
  },
  {
    id: 19,
    name: 'Puma Sneakers',
    brand: 'Puma',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'shoes',
    sold: 7489,
    image: 'images/products/shoes7.jpeg',
    popular: true,
  },
  {
    id: 20,
    name: 'Ducatti Jogging Shoes',
    brand: 'Ducatti',
    price: 24.56,
    originalPrice: 24.56,
    rating: 4.7,
    category: 'shoes',
    sold: 7489,
    image: 'images/products/shoes8.jpeg',
    popular: false,
  },

];

export default products;
